name: Linter

on: [pull_request]

jobs:
  markdown-linter:
    name: "Markdown Linter"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Markdown Linting Action
        uses: avto-dev/markdown-lint@v1.5.0
        with:
          args: '.'
          fix: true
