name: Linter

on: [pull_request]

jobs:
  markdown-linter:
    name: "Markdown Linter"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.2.0
        with:
          files: .
          config_file: .markdownlint.yaml
